
// Action Types
export const FETCH_AUTOCOMPLETE_SUCCESS = 'FETCH_AUTOCOMPLETE_SUCCESS';
export const ADD_TO_SELECTED_PLACE = 'ADD_TO_SELECTED_PLACE';
export const ADD_TO_SEARCH_HISTORY = 'ADD_TO_SEARCH_HISTORY';
